//user reducer types

export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

//ad reducer types
export const NEW_AD = "NEW_AD";
export const INITIATE_AD = "INITIATE_AD";
export const SET_TYPE = "SET_TYPE";
export const SET_CATEGORY = "SET_CATEGORY";
export const LOADING_AD = "LOADING_AD";
export const SAVE_AD = "SAVE_AD";
export const SET_AD = "SET_AD";
export const SET_ADS_BY_USER = "SET_ADS_BY_USER";
export const GET_ALL_ADVERTS = "GET_ALL_ADVERTS";
export const SET_ADVERTS_COUNT = "SET_ADVERTS_COUNT";
// UI reducer types
export const SET_MSG = "SET_MSG";
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const FINISHED_LOADING_UI = "FINISHED_LOADING_UI";
export const LOADING_UPDATEUSER_UI = "LOADING_UPDATEUSER_UI";
export const LOADING_UPLOAD_USER_IMAGE_UI = "LOADING_UPLOAD_USER_IMAGE_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MSG = "CLEAR_MSG";
export const DISABLE_BTN = "DISABLE_BTN";
export const ENABLE_BTN = "ENABLE_BTN";
export const UPLOADING_IMAGE = "UPLOADING_IMAGE";
export const UPLOADDONE_IMAGE = "UPLOADDONE_IMAGE";

export const INPROGRESS1 = "INPROGRESS1";
export const INPROGRESS2 = "INPROGRESS2";
export const INPROGRESS3 = "INPROGRESS3";
export const INPROGRESS4 = "INPROGRESS4";
export const INPROGRESS5 = "INPROGRESS5";

export const PROCESSCOMPLETED1 = "PROCESSCOMPLETED1";
export const PROCESSCOMPLETED2 = "PROCESSCOMPLETED2";
export const PROCESSCOMPLETED3 = "PROCESSCOMPLETED3";
export const PROCESSCOMPLETED4 = "PROCESSCOMPLETED4";
export const PROCESSCOMPLETED5 = "PROCESSCOMPLETED5";

export const DELETE_IMAGE_INPROGRESS1 = "DELETE_IMAGE_INPROGRESS1";
export const DELETE_IMAGE_INPROGRESS2 = "DELETE_IMAGE_INPROGRESS2";
export const DELETE_IMAGE_INPROGRESS3 = "DELETE_IMAGE_INPROGRESS3";
export const DELETE_IMAGE_INPROGRESS4 = "DELETE_IMAGE_INPROGRESS4";
export const DELETE_IMAGE_INPROGRESS5 = "DELETE_IMAGE_INPROGRESS5";

export const DELETE_IMAGE_COMPLETED1 = "DELETE_IMAGE_COMPLETED1";
export const DELETE_IMAGE_COMPLETED2 = "DELETE_IMAGE_COMPLETED2";
export const DELETE_IMAGE_COMPLETED3 = "DELETE_IMAGE_COMPLETED3";
export const DELETE_IMAGE_COMPLETED4 = "DELETE_IMAGE_COMPLETED4";
export const DELETE_IMAGE_COMPLETED5 = "DELETE_IMAGE_COMPLETED5";
