module.exports = {
  categories: [
    "Land",
    "House",
    "Apartment",
    "Room or Annex",
    "Holiday and Short Rental",
    "Commercial Property",
  ],
  categoriesoptionslist: [
    { value: "All", label: "All Categories" },
    { value: "Land", label: "Land" },
    { value: "House", label: "House" },
    { value: "Apartment", label: "Apartment" },
    { value: "Room or Annex", label: "Room or Annex" },
    { value: "Holiday and Short Rental", label: "Holiday and Short Rental" },
    { value: "Commercial Property", label: "Commercial Property" },
  ],
  districts: [
    "Ampara",
    "Anuradhapura",
    "Badulla",
    "Batticaloa",
    "Colombo",
    "Galle",
    "Gampaha",
    "Hambantota",
    "Jaffna",
    "Kalutara",
    "Kandy",
    "Kegalle",
    "Kilinochchi",
    "Kurunegala",
    "Mannar",
    "Matale",
    "Matara",
    "Monaragala",
    "Mullaitivu",
    "Nuwara Eliya",
    "Polonnaruwa",
    "Puttalam",
    "Ratnapura",
    "Trincomalee",
    "Vavuniya",
  ],
  colomboCities: [
    "Angoda",
    "Athurugiriya",
    "Avissawella",
    "Battaramulla",
    "Boralesgamuwa",
    "Colombo 1",
    "Colombo 2",
    "Colombo 3",
    "Colombo 4",
    "Colombo 5",
    "Colombo 6",
    "Colombo 7",
    "Colombo 8",
    "Colombo 9",
    "Colombo 10",
    "Colombo 11",
    "Colombo 12",
    "Colombo 13",
    "Colombo 14",
    "Dehiwala",
    "Hanwella",
    "Homagama",
    "Kaduwela",
    "Kesbewa",
    "Kohuwala",
    "Kolonnawa",
    "Kottawa",
    "Kotte",
    "Malabe",
    "Maharagama",
    "Mount Lavinia",
    "Moratuwa",
    "Nawala",
    "Nugegoda",
    "Padukka",
    "Pannipitiya",
    "Piliyandala",
    "Rajagiriya",
    "Ratmalana",
    "Talawatugoda",
    "Wellampitiya",
  ],
  gampahaCities: [
    "Negombo",
    "Gampaha",
    "Kiribathgoda",
    "Kelaniya",
    "Kadawatha",
    "Delgoda",
    "Divulapitiya",
    "Ganemulla",
    "Ja-Ela",
    "Kandana",
    "Katunayake",
    "Minuwangoda",
    "Mirigama",
    "Nittambuwa",
    "Ragama",
    "Veyangoda",
    "Wattala",
  ],
  kalutaraCities: [
    "Horana",
    "Kalutara",
    "Panadura",
    "Bandaragama",
    "Matugama",
    "Alutgama",
    "Beruwala",
    "Ingiriya",
    "Wadduwa",
  ],
  galleCities: [
    "Galle",
    "Ambalangoda",
    "Elpitiya",
    "Baddegama",
    "Hikkaduwa",
    "Ahangama",
    "Batapola",
    "Bentota",
    "Karapitiya",
  ],
  amparaCities: ["Ampara", "Akkarepattu", "Kalmunai", "Sainthamaruthu"],
  anuradhapuraCities: [
    "Anuradhapura",
    "Kekirawa",
    "Medawachchiya",
    "Tambuttegama",
    "Eppawala",
    "Galenbindunuwewa",
    "Galnewa",
    "Habarana",
    "Mihintale",
    "Nochchiyagama",
    "Talawa",
  ],
  badullaCities: [
    "Badulla",
    "Bandarawela",
    "Welimada",
    "Mahiyanganaya",
    "Hali Ela",
    "Diyatalawa",
    "Ella",
    "Haputale",
    "Passara",
  ],
  batticaloaCities: ["Batticaloa"],
  hambantotaCities: [
    "Tangalla",
    "Beliatta",
    "Ambalantota",
    "Hambantota",
    "Tissamaharama",
  ],
  jaffnaCities: ["Jaffna", "Nallur", "Chavakachcheri"],
  kegalleCities: [
    "Kegalle",
    "Mawanella",
    "Warakapola",
    "Rambukkana",
    "Ruwanwella",
    "Dehiowita",
    "Deraniyagala",
    "Galigamuwa",
    "Kitulgala",
    "Yatiyantota",
  ],
  kandyCities: [
    "Kandy",
    "Katugastota",
    "Gampola",
    "Peradeniya",
    "Kundasale",
    "Akurana",
    "Ampitiya",
    "Digana",
    "Galagedara",
    "Gelioya",
    "Kadugannawa",
    "Madawala Bazaar",
    "Pilimatalawa",
    "Wattegama",
  ],
  kilinochchiCities: ["Kilinochchi"],
  kurunegalaCities: [
    "Kurunegala",
    "Kuliyapitiya",
    "Narammala",
    "Pannala",
    "Wariyapola",
    "Alawwa",
    "Bingiriya",
    "Galgamuwa",
    "Giriulla",
    "Hettipola",
    "Ibbagamuwa",
    "Mawathagama",
    "Nikaweratiya",
    "Polgahawela",
  ],
  mannarCities: ["Mannar"],
  mataleCities: [
    "Matale",
    "Dambulla",
    "Galewela",
    "Ukuwela",
    "Palapathwela",
    "Rattota",
    "Sigiriya",
    "Yatawatta",
  ],
  mataraCities: [
    "Matara",
    "Weligama",
    "Akuressa",
    "Hakmana",
    "Dikwella",
    "Deniyaya",
    "Kamburugamuwa",
    "Kamburupitiya",
    "Kekanadurra",
  ],
  monaragalaCities: [
    "Monaragala",
    "Wellawaya",
    "Bibile",
    "Buttala",
    "Kataragama",
  ],
  mullativuCities: ["Mullativu"],
  nuwaraeliyaCities: ["Nuwara Eliya", "Hatton", "Ginigathhena", "Madulla"],
  polonnaruwaCities: [
    "Polonnaruwa",
    "Kaduruwela",
    "Hingurakgoda",
    "Medirigiriya",
  ],
  puttalamCities: [
    "Chilaw",
    "Wennappuwa",
    "Puttalam",
    "Nattandiya",
    "Dankotuwa",
    "Marawila",
  ],
  ratnapuraCities: [
    "Ratnapura",
    "Embilipitiya",
    "Balangoda",
    "Pelmadulla",
    "Eheliyagoda",
    "Kuruwita",
  ],
  trincomaleeCities: ["Trincomalee", "Kinniya"],
  vavuniyaCities: ["Vavuniya"],
  landTypes: ["Agricultural", "Commercial", "Residential", "Other"],
  landSizes: ["perches", "acres"],
  priceUnits: ["Total price", "per perch", "per acre"],
  bathsbeds: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "10+"],
  propertytype_commercialproperty: [
    "Building",
    "Factory / Workshop",
    "Hotel",
    "Office",
    "Restaurant",
    "Shop",
    "Warehouse / Storage",
    "Other",
  ],
  propertytype_holidayshortrental: [
    "Apartment",
    "Holiday Bunglow",
    "Seasonal room",
    "Other",
  ],
  propertytype_roomannex: ["Annex", "Apartment", "House", "Portion", "Other"],
};
