module.exports = {
  ADVERT_STATUS_NEW: "NEW",
  ADVERT_STATUS_EDIT: "EDIT",
  ADVERT_STATUS_INREVIEW: "IN REVIEW",
  ADVERT_STATUS_NEEDEDIT: "NEED EDIT",
  ADVERT_STATUS_LIVE: "LIVE",
  ADVERT_STATUS_EXPIRED: "EXPIRED",

  PAYMENT_STATUS_FREE: "FREE",
  PAYMENT_STATUS_NOT_PAID: "NOT PAID",
  PAYMENT_STATUS_PAID: "PAID",
  PAYMENT_STATUS_MEMBERSHIP: "MEMBERSHIP",
};
